[theme]
primaryColor = "#4CAF50"  # Color principal (botones, énfasis)
backgroundColor = "#FFFFFF"  # Color del fondo general
secondaryBackgroundColor = "#F0F0F5"  # Color del fondo de la barra lateral
textColor = "#262730"  # Color del texto principal
font = "sans serif"  # Tipo de fuente
